version: '3.8'

services:
  appium-tests:
    image: maven:3.9.6-eclipse-temurin-17
    container_name: mobile_automation_runner
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - ADB_SERVER_SOCKET=tcp:10.36.64.122:5037  # ✅ Updated with your machine's local IP
    command: mvn clean test -DsuiteXmlFile=fulltestng.xml